services:
  - type: web
    name: stock-advisor-api
    runtime: python
    region: oregon
    plan: free
    repo: https://github.com/jya507872/stock-advisor
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
